### PR TITLE
Fix filtering notes, status bug, missing offset/limit functonality

### LINKED ISSUE #43: Update errors to be more specific
- [x] Command specific errors (missing tag or fail tag requirements)
  > e.g. add command missing n/ doesnt specifically say missing n/

### LINKED ISSUE #52: Fix AddContact error checking for invalid tags
Fix error throwing for commands like
```addcontact n/test p/1234954 abc/```

Original:

Image

### LINKED ISSUE #53: Fix filtering notes, status bug, missing offset/limit functonality
### Known bug 1
- User inserts notes as having a "/" e.g. ```notes/this contact wants yishun/orchard properties```
- During filtering command ```filtercontact notes/yishun/orchard``` will return error as program will see ```/orchard``` as an invalid prefix
    > currently use ```string.contains("/")``` to check for invalid prefixes
    > seems correct as every other attribute shouldn't have "/"
    > to make sure notes is not checked for "/"

### Known bug 2
- filtering ```s/active``` also returns inactive persons

### Known bug 3
- limit & offset not yet implemented

### PR DESCRIPTION
**Pull request by joojaja**
Resolves #53
Resolves #52
Resolves #43 

- [x] Add error checking and JUnit testing for budget max < budget min
- [x] Fix bug 1-3 from #53 
- [x] Fix bug 4 from #52 

### Known bug 1 (✅ RESOLVED)
- User inserts notes as having a "/" e.g. ```notes/this contact wants yishun/orchard properties```
- During filtering command ```filtercontact notes/yishun/orchard``` will return error as program will see ```/orchard``` as an invalid prefix
    > currently use ```string.contains("/")``` to check for invalid prefixes
    > seems correct as every other attribute shouldn't have "/"
    > to make sure notes is not checked for "/"

### Known bug 2 (✅ RESOLVED)
- filtering ```s/active``` also returns inactive persons

### Known bug 3 (✅ RESOLVED)
- limit & offset not yet implemented

### Known bug 4 (✅ RESOLVED)
Fix error throwing for commands like
addcontact n/test p/1234954 abc/
addcontact abc/

#### Original:

Image

#### Resolved: 

image

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -92,7 +92,7 @@ public CommandResult execute(Model model) throws CommandException {
         Person personToEdit = lastShownList.get(index.getZeroBased());
         Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
 
-        if (!personToEdit.isSamePerson(editedPerson) && model.hasPerson(editedPerson)) {
+        if (!personToEdit.equals(editedPerson) && model.hasPerson(editedPerson)) {
```
Comment (MNJPeng) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: A little confused here. Any specific reason for this change in logic?

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 2]
```diff
@@ -87,7 +106,14 @@ public AddCommand parse(String args) throws ParseException {
...
     private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
-        return Stream.of(prefixes).allMatch(prefix -> argumentMultimap.getValue(prefix).isPresent());
+        return !Stream.of(prefixes).allMatch(prefix -> argumentMultimap.getValue(prefix).isPresent());
+    }
+
+    /**
+     * Returns true if the given string looks like an unrecognized prefix (e.g., "x/foo").
+     */
+    private boolean looksLikePrefix(String s) {
+        return s.trim().contains("/");
```
[the remark this answers is not in the document]
Comment (MNJPeng) [reply src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Just saw it used in `FilterContactCommandParser` as well. Suggest placing it in ParserUtil to avoid code duplication.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 3]
```diff
@@ -107,18 +107,27 @@ public static Phone parsePhone(String phone) throws ParseException {
...
+     * This method helps simplify null checks when parsing optional user inputs.
+     *
+     * @param value the input string, which may be {@code null}
+     * @param defaultValue the fallback string to use if {@code value} is {@code null}
+     * @return {@code value} if non-null, otherwise {@code defaultValue}
+     */
+    private static String sanitiseNull(String value, String defaultValue) {
+        return value == null ? defaultValue : value;
+    }
+
```
Comment (MNJPeng) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Nice abstraction

File: src/main/java/seedu/address/model/person/Person.java [hunk 4]
```diff
@@ -122,24 +136,11 @@ public Set<String> getSellingPropertyIds() {
...
-    public boolean isSamePerson(Person otherPerson) {
-        if (otherPerson == this) {
-            return true;
-        }
-
-        return otherPerson != null
-                && otherPerson.getName().equals(getName())
-                && otherPerson.getPhone().equals(getPhone());
-    }
-
```
Comment (MNJPeng) [inline src/main/java/seedu/address/model/person/Person.java]: Is the weaker notion of equality not useful here? I would assume the higher level idea is that there should not be any 2 contacts with the same name and phone number

File: src/main/java/seedu/address/model/person/Person.java [hunk 5]
```diff
@@ -122,24 +136,11 @@ public Set<String> getSellingPropertyIds() {
...
     /**
      * Returns true if both persons have the same name & same phone number.
      */
     @Override
-    public boolean equals(Object other) { //TODO merge equals with isSamePerson?
+    public boolean equals(Object other) {
         if (other == this) {
             return true;
         }
```
Comment (monnss69) [inline src/main/java/seedu/address/model/person/Person.java]: I think you must merge it with isSamePerson before apply it everywhere

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 1 above)
Comment (joojaja) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: weaker notation of equality is same as higher notation of equality. a Person is same as another Person if and only if name+phone is same.

File: src/main/java/seedu/address/model/person/Person.java (hunk 5 above)
Comment (joojaja) [reply src/main/java/seedu/address/model/person/Person.java]: has been applied everywhere
