### PR TITLE
addcontact v1.4 bug fixes

### LINKED ISSUE #130: addcontact missing compulsory parameters should say which is missing
To recreate bug

addcontact n/CHARLIE e/test@gmail.com a/982 Tampines Road t/buyer s/active

### LINKED ISSUE #131: GUI of contacts not showing all parameters (budget, status etc)

### LINKED ISSUE #132: Format of invalid input Status/Tag should say case insensitive. Allow empty tag input
status format saying '' is allowed also remove
or allow tag to also have ''

### LINKED ISSUE #133: addcontact console printing missing details

### LINKED ISSUE #134: Error printing in console make more readable
- [ ] error for budget max less than budget min make readable format
- [ ] error for budget min negative
- [ ] email invalid error too hard to read?
- [ ] specific error: doesnt fit valid format for phone/address etc
> to allow does / in address or email? to check

extra / in phone
addcontact n/CHARLIE p/91/236789 a/982 Tampines Road t/buyer s/active

extra / in address
addcontact n/CHARLIE p/91236789 a/9/82 Tampines Road t/buyer s/active

email error
addcontact n/CHARLIE p/91236789 e/test@gmail a/982 Tampines Road t/buyer s/active

### LINKED ISSUE #135: addcontact: Extra spacing between name and surname still has error
error for extra space between name and surname

to recreate:
addcontact n/CHARLIE    test p/91236789 a/982 Tampines Road t/buyer s/active

### LINKED ISSUE #136: s/ should not be parameter as name can have s/o
to recreate:
addcontact n/CHARLIE s/o test p/91236789 a/982 Tampines Road t/buyer s/active

### PR DESCRIPTION
**Pull request by joojaja**
This PR fixes the bugs in `addcontact` command from the alpha release

Resolves #130 
- [x] missing which compulsory parameters should say error which parameter missing (for example n/NAME missing should say exactly that name is missing)

Resolve #131 
- [x] GUI of contacts not showing all details
- [x] If detail is empty (e.g. status is empty) then dont even have the line "Status: " in GUI (do for all optional parameters)

Resolve #132 
- [x] Status/Tag error should say case-insensitive
- [x] Allow empty tag input
- [x] Ensure optional paramters can have empty inputs (addcontact n/Charlie p/91236789 e/ a/ min/ max/ t/ notes/ s/)

Resolves #133 
- [x] addcontact success message in console missing some details

Resolves #134 
- [x] Error msg for budget max less than budget min make readable format
- [x] Error msg for budget min negative
- [x] AB3 Email message constraint too hard to read, make it readable
- [x] Email constraint from AB3 is wrong
- [x] Specific error if there is "/" in parameter instead of general error

Resolves #135 
- [x] Error for extra space between name and surname still outputs error
addcontact n/CHARLIE    test p/91236789 a/982 Tampines Road t/buyer s/active

Resolves #136 
- [x] s/ should not be status parameter as s/o (son of) needed in name. to change to use status/ instead
addcontact n/bob s/o alex p/1235

### CODE REVIEW

**Review by wengmu — COMMENTED** [review]
LGTM, but might want to edit the section of the code that contains deep nesting

File: src/main/java/seedu/address/logic/parser/AddContactCommandParser.java [hunk 1]
```diff
@@ -94,4 +80,95 @@ public AddContactCommand parse(String args) throws ParseException {
...
+            return String.format(MESSAGE_INVALID_COMMAND_FORMAT, BudgetMin.MESSAGE_CONSTRAINTS);
+        } else if (prefix.equals(PREFIX_BUDGET_MAX)) {
+            return String.format(MESSAGE_INVALID_COMMAND_FORMAT, BudgetMax.MESSAGE_CONSTRAINTS);
+        } else if (prefix.equals(PREFIX_STATUS)) {
+            return String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                    String.format(ContactStatus.MESSAGE_CONSTRAINTS, value));
+        } else {
+            return String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddContactCommand.MESSAGE_USAGE);
+        }
+    }
```
Comment (MNJPeng) [inline src/main/java/seedu/address/logic/parser/AddContactCommandParser.java]: Perhaps better to replace with a switch case?

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -191,7 +196,7 @@ public static Set<Tag> parseTags(Collection<String> tags) throws ParseException
      * @throws ParseException if the given {@code budgetMin} is not a valid integer or violates constraints.
      */
     public static BudgetMin parseBudgetMin(String budgetMin) throws ParseException {
-        String trimmedBudgetMin = sanitiseNull(budgetMin, "0").trim();
+        String trimmedBudgetMin = sanitiseNull(budgetMin, DEFAULT_BUDGET_MIN).trim();
```
Comment (MNJPeng) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Nice abstractions

File: src/main/java/seedu/address/model/contact/Email.java [hunk 3]
```diff
@@ -10,26 +10,32 @@
...
-    private static final String ALPHANUMERIC_NO_UNDERSCORE = "[^\\W_]+"; // alphanumeric characters except underscore
-    private static final String LOCAL_PART_REGEX = "^" + ALPHANUMERIC_NO_UNDERSCORE + "([" + SPECIAL_CHARACTERS + "]"
+    public static final String MESSAGE_CONSTRAINTS =
+            "Emails should follow the format: name@example.com\n"
+            + "• The part before @ can contain letters, numbers, and the symbols " + SPECIAL_CHARACTERS + "\n"
+            + "• It cannot start or end with a symbol\n"
+            + "• The part after @ must be a valid domain (like example.com)\n"
+            + "• The domain must end with at least 2 letters (like .com or .sg)\n"
+            + "• You can also leave the email field empty\n"
+            + "• Emails can also be left empty";
```
Comment (MNJPeng) [inline src/main/java/seedu/address/model/contact/Email.java]: Are these 2 different?

File: src/main/java/seedu/address/ui/ContactCard.java [hunk 4]
```diff
@@ -44,27 +47,123 @@ public class ContactCard extends UiPart<Region> {
...
         phone.setText("Phone: " + contact.getPhone().value);
-        address.setText("Address: " + contact.getAddress().value);
-        email.setText("Email: " + contact.getEmail().value);
-        contact.getTags().stream()
-                .sorted(Comparator.comparing(tag -> tag.tagName))
-                .forEach(tag -> tags.getChildren().add(new Label(tag.tagName)));
-
-        String formattedLinkedIds = String.format("Buying Ids: %s • Selling Ids: %s",
-                Uuid.getGuiSetDisplayAsString(contact.getBuyingPropertyIds()),
-                Uuid.getGuiSetDisplayAsString(contact.getSellingPropertyIds()));
```
Comment (MNJPeng) [inline src/main/java/seedu/address/ui/ContactCard.java]: If the `Uuid.getGuiSetDisplayAsString` method is no longer needed, would be good to remove it

Also makes sense to update Propertycard to the same format?

**Review by MNJPeng — COMMENTED** [review]
Additional comments linked to previous review

File: src/main/java/seedu/address/logic/parser/AddContactCommandParser.java (hunk 1 above)
Comment (joojaja) [reply src/main/java/seedu/address/logic/parser/AddContactCommandParser.java]: unable to switch case prefix objects. switch case only can be used with primitives

File: src/main/java/seedu/address/ui/ContactCard.java [hunk 5]
```diff
@@ -44,27 +47,123 @@ public class ContactCard extends UiPart<Region> {
...
+     * @param prefix The prefix text
+     * @param ids The set of UUIDs to display.
+     */
+    private void setIdsIfNotEmpty(Label label, String prefix, java.util.Set<Uuid> ids) {
+        if (ids.isEmpty()) {
+            hideLabel(label);
+        } else {
+            label.setText(prefix + Uuid.getGuiSetDisplayAsString(ids));
+        }
     }
```
[the remark this answers is not in the document]
Comment (joojaja) [reply src/main/java/seedu/address/ui/ContactCard.java]: agreed. maybe once we get to the property card we can handle it
