### PR TITLE
Bugfixes for PE Dry Run

### LINKED ISSUE #223: [PE-D][Tester D] Jar file provided in the release is named differently from stated in the user guide, leading to issues in launching the application if following the user guide
After downloading the jar file provided in release TheRealDeal v1.5, I followed the user guide steps in order to start up the application. Specifically, I followed step 4 of the Quick Start section in the User Guide, provided below.

Step 4. Open a command terminal, cd into the folder you put the jar file in, and use the `java -jar TheRealDeal.jar` command to run the application.

However, after running the command, I was unable to run the application and instead received this error in my command terminal: 
**Error: Unable to access jarfile TheRealDeal.jar**

Image

I believe this error was received due to the name of the jar file being "TheRealDeal-v1.5-all.jar" instead of "TheRealDeal.jar". I think it might be better to standardize the naming convention of the jar file to fit the User guide. 

I labeled this as a high severity bug as all users would download this jar file to use the application, hence this bug would affect all users. Additionally non-technical users following the user guide might not understand why the application is unable to run, and this would prevent them from using the application at all. 

-------------
Labels: `severity.High` `type.DocumentationBug`

### LINKED ISSUE #228: [PE-D][Tester D] Deleting a contact does not remove it from being linked to a property
Below are the steps to reproduce this bug 
1. Link a contact to a property using `link c/3 p/4 r/buyer`, supposing there is a contact with ID 3 and property with ID 4
2. Delete the contact with ID 3 using `deletecontact 3`. Note that new list shows that the contact with ID 3 is deleted.
3. List out all the properties using `filterproperty`

After listing out all the properties, you can see that the property with ID 4 still has a buyer with ID 3, even though there is no longer a contact with ID 3. 

Is it perhaps possible to unlink any linked properties to the contact being deleted when executing a `deletecontact` command? 

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #230: [PE-D][Tester D] Deleting a property does not remove it from being linked to a contact
Below are the steps to reproduce this bug
1. Link a property to a contact using `link c/3 p/4 r/buyer`, supposing there is a contact with ID 3 and property with ID 4
2. Delete the property with ID 4 using `deleteproperty 4`. Note that new list shows that the property with ID 4 is deleted.
3. List out all the contacts using `filtercontact`.

After listing out all the contacts, you can see that the contact with ID 3 still has a property with ID 4 as a "Buying Property ID", even though there is no longer a property with ID 4.

Is it perhaps possible to unlink any linked contacts to the property being deleted when executing a `deleteproperty` command?

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #237: [PE-D][Tester C] Link command: improve message view, inconvenience when testing
Summary: 
Since there are two different views, a properties list and a contacts view. I need to toggle between the two views to get the necessary ID in order to link them. 

This makes testing inconvenient.

The message in command result then tells the IDs that were linked but I can't recall what the details were. Better if it could also show more information on the property and contact that was linked. 

Steps to reproduce
1. type `filtercontact`
2. find ID of the contact you want to link such as 3
3. type `filterproperty`
4. find ID of the property you want to link such as 1
5. type `link c/3 r/buyer p/1`

GUI output after executing:

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #244: [PE-D][Tester D] showproperties still shows properties linked to deleted contacts
To reproduce this bug: 
1. Link a property to a contact using `link c/3 p/4 r/buyer`, supposing there is a contact with ID 3 and property with ID 4
2. Delete the contact with ID 3 using `deletecontact 3`. Note that new list shows that the contact with ID 3 is deleted.
3. Show the properties linked to contact ID 3 with `showproperties 3`

Even though this should be an invalid input to the `showproperties` command as there is no longer a contact with ID 3, it still shows the properties that were previously linked to contact ID 3 before the contact was deleted.

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #260: [PE-D][Tester E] References of Link in Unlink section of User Guide
There are two references to Link in the Unlink section of the User Guide as shown below:

Image

The first reference is in the command format which is an essential part of this section. The second reference is in the first bullet point which describes what the command does. While it is clear that these are typos, it is better to proofread for typos like these. The command format being wrong could actually cause confusion amongst first time users.

-------------
Labels: `severity.Medium` `type.DocumentationBug`

### LINKED ISSUE #275: [PE-D][Tester A] It is possible for an owner to be a buyer to their own property
This might be an unexpected behaviour. See entry 11:
Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #276: [PE-D][Tester E] Unclear relationship between contacts and properties in Link/Unlink
Given a command like 'link c/1 c/2 c/3 r/buyer p/1 p/2 p/3', it is unclear from the user guide description whether the contact-property relationship is one-to-one (that is, c/1 links to p/1, c/2 links to p/2 and c/3 links to p/3) or a 'for each property, link each buyer to that property'. 

It was a good option to go with the second relationship as a contact can be linked to more than one properties in just one command (link c/1 r/buyer p/1 p/2 p/3) but it may be good to clarify this exact relationship in the User Guide for first time users. 

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #283: [PE-D][Tester B] A sold/unavailble property can be link to a new buyer
There is a logic constraint that fails to be enforced. A sold/unavailable property can be linked to a new buyer. 
Logically speaking, there should be a check done here so that it prevents the linking of this property to this new buyer.

Codes executed
```
clear
addcontact n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/buyer t/seller
addproperty a/123 Orchard Rd postal/238888 type/condo bed/3 bath/2 f/1023 price/1950000 status/unavailable l/sale o/1
link p/1 r/buyer c/1 
```
Output: Instead of preventing the linking between this property and the new buyer, the link command runs
Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #296: UUID.toString() to remove itemType.name() for clarity
to reproduce
1. delete all data/use default data
2. `editcontact 1 n/abc`

see console as below

`Selling Property Ids: [1 (PROPERTY)]` could be misleading. same problem occurs with adding contact 

Image

### PR DESCRIPTION
**Pull request by MNJPeng**
Resolves #237 , Resolves #275 
Rejected. Reasons listed in issues

Resolves #296 
UUID.toString no longer displays `(Property)` or `(Contact)`

Resolves #223 
Updated UG Quick start to be more generic with Jar file names

Resolves #228 , Resolves #230 , Resolves #244 
Deleting now unlinks contacts and properties

Resolves #260 
Updated UG with correct unlink command

Resolves #276 
Updated UG command description of `link` to indicate all contacts are linked to all properties

Resolves #283 
Unavailable properties can no longer be linked to. Unlinking is still possible.
UG is also updated to reflect changes

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java [hunk 1]
```diff
@@ -34,6 +37,7 @@ public DeletePropertyCommand(Uuid targetPropertyId) {
 
     @Override
     public CommandResult execute(Model model) throws CommandException {
+        // assert false;
```
Comment (joojaja) [inline src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java]: can be removed
